// <auto-generated />
namespace MyShop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddBasket_FixSpelling_Mistake : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBasket_FixSpelling_Mistake));
        
        string IMigrationMetadata.Id
        {
            get { return "201907151559510_AddBasket_FixSpelling_Mistake"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
